name: Create Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-release:
    name: Build and Release
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v1.5.2
      ci_tools_version: main
      extension_name: financial_functions
      extra_toolchains: "rust;python3"
      exclude_archs: "wasm_mvp;wasm_eh;wasm_threads;linux_amd64;linux_arm64;linux_amd64_musl;linux_arm64_musl"
      deploy_as: ${{ github.ref_name }}
